version: '3.8'

volumes:
  wordpress:
    name: wordpress
    driver_opts:
      type: none
      device: /home/amuhleth/data/wordpress

  db:
    name: db
    driver_opts:
      type: none
      device: /home/amuhleth/data/db

services:
  nginx:
    build:
      context: requirements/nginx
      dockerfile: Dockerfile
    container_name: nginx
    networks:
      - network
    volumes:
      - wordpress:/var/www/wordpress

  wordpress:
    build:
      context: requirements/wordpress
      dockerfile: Dockerfile
    container_name: wordpress
    networks:
      - network
    volumes:
      - wordpress:/var/www/wordpress

  mariadb:
    build:
      context: requirements/mariadb
      dockerfile: Dockerfile
    container_name: mariadb
    networks:
      - network
    volumes:
      - db:/val/lib/mysql

networks:
  network:
    name: network
